services:
  mongodb:
    build:
      context: .
      dockerfile: dockerfile
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: podaci
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./dump:/dump
      - ./exports:/exports
    networks:
      - app-network

  backend:
    build:
      context: ./backend  
    container_name: backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydb  
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./app 
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
