services:
  mongodb:
    build:
      context: .
      dockerfile: dockerfile
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: podaci
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./dump:/dump
      - ./exports:/exports
    networks:
      - app-network

  backend:
    build:
      context: ./backend  # Assuming your backend code is in the 'backend' folder
    container_name: backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydb  # Adjust for your MongoDB connection
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongodb

  # Frontend Service (Flutter Web App)
  frontend:
    build:
      context: ./app  # Assuming your Flutter web code is in the 'frontend' folder
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
