# Use an official Node.js runtime as a parent image
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install backend dependencies
RUN npm install express mongodb cors

# Copy the rest of the application code
COPY . .

# Expose the port the backend will run on
EXPOSE 3000

# Run the backend
CMD ["node", "index"]
